language: python
python:
  - "3.9"
install:
  - git clone https://github.com/hannorein/rebound rebound-src
  - pip install mypy matplotlib
  - pip install git+https://github.com/Findus23/retype.git@skip-setters
  # stub-dir, output dir, src dir
  - retype -p rebound -t retyped/rebound rebound-src/rebound
  - cd retyped && mypy rebound || true
