from multiprocessing.pool import Pool
from typing import Any, Optional

class InterruptiblePool(Pool):
    wait_timeout: int = ...
    def __init__(self, processes: Optional[Any] = ..., initializer: Optional[Any] = ..., initargs: Any = ..., **kwargs: Any) -> None: ...
    def map(self, func: Any, iterable: Any, chunksize: Optional[Any] = ...): ...
