# from . import clibrebound as clibrebound
# from ctypes import byref as byref, c_float as c_float, create_string_buffer as create_string_buffer
# from ipywidgets import DOMWidget
# from typing import Any, Optional
#
# shader_code: str
# js_code: str
# ipywidgets_major_version: Any
#
# def savescreenshot(change: Any) -> None: ...
#
# class Widget(DOMWidget):
#     count: Any = ...
#     screenshotcount: Any = ...
#     t: Any = ...
#     N: Any = ...
#     overlay: Any = ...
#     width: Any = ...
#     height: Any = ...
#     scale: Any = ...
#     particle_data: Any = ...
#     orbit_data: Any = ...
#     orientation: Any = ...
#     orbits: Any = ...
#     screenshot: Any = ...
#     screenshotcountall: int = ...
#     autorefresh: Any = ...
#     useroverlay: Any = ...
#     simp: Any = ...
#     def __init__(self, simulation: Any, size: Any = ..., orientation: Any = ..., scale: Optional[Any] = ..., autorefresh: bool = ..., orbits: bool = ..., overlay: bool = ...) -> None: ...
#     def refresh(self, simp: Optional[Any] = ..., isauto: int = ...) -> None: ...
#     archive: Any = ...
#     screenshotprefix: Any = ...
#     times: Any = ...
#     mode: Any = ...
#     def takeScreenshot(self, times: Optional[Any] = ..., prefix: str = ..., resetCounter: bool = ..., archive: Optional[Any] = ..., mode: str = ...) -> None: ...
#     @staticmethod
#     def getClientCode(): ...
